# This file was generated by the {rix} R package v0.17.2 on 2025-11-22
# with following call:
# >rix(date = c(latest,
#  > "2025-11-03",
#  > "2025-11-01",
#  > "2025-08-18")[1],
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > ide = c("positron",
#  > "rstudio")[1],
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-03.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      arrow
      autometric
      available
      covr
      crew
      dbplyr
      devtools
      dplyr
      DT
      duckdb
      furrr
      future
      future_apply
      gert
      ggdist
      ggplot2
      ggraph
      ggtext
      ggview
      gh
      gittargets
      here
      httptest
      igraph
      jsonlite
      keyring
      knitr
      logger
      lubridate
      mcptools
      mirai
      nanonext
      ollamar
      pins
      pkgdown
      plotly
      promises
      purrr
      quarto
      reticulate
      riingo
      rix
      rmarkdown
      rnaturalearth
      sf
      shiny
      shinydashboard
      shinyjs
      spelling
      stringr
      styler
      tarchetypes
      targets
      testthat
      tidyfinance
      tidymodels
      tidyquant
      tidyselect
      tidytuesdayR
      tidyverse
      units
      usethis;
  };
 
    btw = (pkgs.rPackages.buildRPackage {
      name = "btw";
      src = pkgs.fetchgit {
        url = "https://github.com/posit-dev/btw";
        rev = "692db86d23d1ff9d19d32802588b91c294d01c10";
        sha256 = "sha256-HnL22ePajrUXU/f7PtajjX9Wvaq78jqUCJ2Z2VeoNY8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          clipr
          dplyr
          ellmer
          fs
          jsonlite
          lifecycle
          mcptools
          pkgsearch
          rlang
          rmarkdown
          rstudioapi
          S7
          sessioninfo
          skimr
          tibble
          withr
          xml2
          #<- if (getRversion() < 4_3_0) S7;
          ;
      };
    });

    randomwalk = (pkgs.rPackages.buildRPackage {
      name = "randomwalk";
      src = pkgs.fetchgit {
        url = "https://github.com/johngavin/randomwalk";
        rev = "cfe17e3f988be40453a31432876d3a9cb404c8be";
        sha256 = "sha256-d+fqEWqikwkKvkB54tkiI470gsw7itdpHHFo5EwDX38=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          logger
          ggplot2;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      cmdstan
      curlMinimal
      duckdb
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      less
      libiconv
      nano
      nix
      nodejs
      ollama
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    #<- buildInputs = [ randomwalk btw rpkgs system_packages ];
    buildInputs = [ randomwalk btw ] ++ rpkgs ++ system_packages;
    shellHook = ''
      # Randomwalk development environment
      unset CI
      echo "Randomwalk Nix environment ready."
      echo "R version: $(R --version | head -1)"
    '';
  }; 
in
  {
    inherit pkgs shell;
  }
