# This file was generated by the {rix} R package v0.17.2 on 2025-11-19
# with following call:
# >rix(date = c(latest,
#  > "2025-11-03",
#  > "2025-11-01",
#  > "2025-08-18")[1],
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > ide = c("positron",
#  > "rstudio")[1],
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-03.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      ape
      arrow
      askpass
      autometric
      available
      aws_s3
      base64enc
      beepr
      BiocManager
      Biostrings
      blockCV
      brio
      broom
      broom_mixed
      bsicons
      caret
      CAST
      ComplexHeatmap
      covr
      coxme
      crew
      dagitty
      data_table
      dbplyr
      devtools
      digest
      dotenv
      dplyr
      DT
      duckdb
      elevatr
      ellmer
      emmeans
      forcats
      fs
      furrr
      future
      future_apply
      gert
      ggdag
      ggdist
      ggplot2
      ggraph
      ggridges
      ggtext
      ggview
      gh
      gittargets
      glue
      here
      httptest
      igraph
      ISOcodes
      janitor
      jsonlite
      keyring
      knitr
      leaflet
      logger
      lubridate
      maftools
      magick
      mcptools
      mirai
      nanonext
      ollamar
      osmdata
      patchwork
      pins
      pkgdown
      plotly
      promises
      purrr
      quarto
      ragnar
      ranger
      reactable
      readr
      reticulate
      riingo
      rix
      rixpress
      rmarkdown
      rnaturalearth
      rsdmx
      scales
      sf
      shiny
      shinychat
      shinydashboard
      shinyjs
      shinylive
      simstudy
      spelling
      stringr
      styler
      survival
      survminer
      tarchetypes
      targets
      terra
      testthat
      tidyfinance
      tidymodels
      tidyquant
      tidyr
      tidyselect
      tidytuesdayR
      tidyverse
      units
      usethis
      vitals
      watcher
      weathR
      WikidataR;
  };
 
    btw = (pkgs.rPackages.buildRPackage {
      name = "btw";
      src = pkgs.fetchgit {
        url = "https://github.com/posit-dev/btw";
        rev = "692db86d23d1ff9d19d32802588b91c294d01c10";
        sha256 = "sha256-HnL22ePajrUXU/f7PtajjX9Wvaq78jqUCJ2Z2VeoNY8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          clipr
          dplyr
          ellmer
          fs
          jsonlite
          lifecycle
          mcptools
          pkgsearch
          rlang
          rmarkdown
          rstudioapi
          S7
          sessioninfo
          skimr
          tibble
          withr
          xml2
          #<- if (getRversion() < 4_3_0) S7;
          ;
      };
    });

    randomwalk = (pkgs.rPackages.buildRPackage {
      name = "randomwalk";
      src = pkgs.fetchgit {
        url = "https://github.com/johngavin/randomwalk";
        rev = "cfe17e3f988be40453a31432876d3a9cb404c8be";
        sha256 = "sha256-d+fqEWqikwkKvkB54tkiI470gsw7itdpHHFo5EwDX38=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          logger
          ggplot2;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      claude-code
      cmdstan
      copilot-cli
      curlMinimal
      duckdb
      gemini-cli
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      less
      libiconv
      nano
      nix
      nodejs
      ollama
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    #<- buildInputs = [ randomwalk btw rpkgs system_packages ];
    buildInputs = [ randomwalk btw ] ++ rpkgs ++ system_packages;
    shellHook = "
# GEMINI setup
# CI environment variable (which stands for Continuous Integration) signals to Node.js applications like the gemini-cli that they are running in a non-interactive, automated environment
unset CI ; 
# confirm api key else cat ~/.gemini/.env?
cat ~/.gemini/.env ; 
# confirm quarto is inside nix
echo $ANTHROPIC_API_KEY
which nodejs tinytex curl nano duckdb tree awscli2 bc ollama gh git less unzip
# Add to shell startup
echo '$(date): Nix shell started' >> ~/.nix-session.log
echo 'PATH: $PATH' >> ~/.nix-session.log

";
  }; 
in
  {
    inherit pkgs shell;
  }
