# This file was generated by the {rix} R package v0.17.2 on 2025-11-20
# with following call:
# >rix(r_ver = "1482d00f8f658fd443526febba6c9fd9754cb356",
#  > r_pkgs = r_pkgs_ci,
#  > system_pkgs = system_pkgs_ci,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = NULL)
# It uses upstream nixpkgs' revision 1482d00f8f658fd443526febba6c9fd9754cb356 for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/1482d00f8f658fd443526febba6c9fd9754cb356.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covr
      crew
      devtools
      dplyr
      duckdb
      ggplot2
      knitr
      logger
      munsell
      nanonext
      pkgdown
      quarto
      rcmdcheck
      rmarkdown
      roxygen2
      shiny
      shinylive
      tarchetypes
      targets
      testthat
      visNetwork;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      curlMinimal
      gh
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
