# This file was generated by the {rix} R package v0.17.4 on 2026-02-15
# with following call:
# >rix(date = "2026-01-05",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covr
      crew
      devtools
      dplyr
      duckdb
      gert
      ggplot2
      knitr
      logger
      nanonext
      pkgdown
      quarto
      rmarkdown
      roxygen2
      shiny
      shinytest2
      tarchetypes
      targets
      testthat
      visNetwork;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      gh
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      tree
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
