# This file was generated by the {rix} R package v0.17.2 on 2025-11-20
# with following call:
# >rix::rix(r_ver = "0441ffc921a7354db54d0f2eee28a57187aceb4f",
#  > r_pkgs = ci_packages,
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = tmp_project,
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = NULL)
# It uses upstream nixpkgs' revision 0441ffc921a7354db54d0f2eee28a57187aceb4f for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/0441ffc921a7354db54d0f2eee28a57187aceb4f.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covr
      crew
      devtools
      ggplot2
      knitr
      logger
      nanonext
      pkgdown
      rcmdcheck
      rmarkdown
      roxygen2
      shinylive
      testthat;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
