# This file was generated by the {rix} R package v0.17.2 on 2025-09-11
# Minimal rix environment for regenerating default.nix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-04-29.tar.gz") {};

    rix = (pkgs.rPackages.buildRPackage {
      name = "rix";
      src = pkgs.fetchgit {
        url = "https://github.com/ropensci/rix/";
        rev = "2213ee545640f44951d0bd71b9317df2463599d3";
        sha256 = "sha256-KuwztCi5GO/NyRVJu1m4hD0uNrBUmdpo3HrGY2bhrB0=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          codetools
          curl
          jsonlite
          sys;
      };
    });

    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/b-rodrigues/rixpress/";
        rev = "93cda39228e5539530e4dea61f3092e32b426f54";
        sha256 = "sha256-ZegyVnsgwBgSgdW73xupD5Il5Ejjo4G6fh3A7WhAlhc=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          igraph
          jsonlite
          processx;
      };
    });

  system_packages = builtins.attrValues {
    inherit (pkgs)
      glibcLocales
      nix
      R;
  };

  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ rix rixpress pkgs.rPackages.usethis system_packages ];

  };
in
  {
    inherit pkgs shell;
  }
