name: Build WebR Binaries

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggers for testing

permissions:
  contents: read
  repository-projects: read   # Needed to access GitHub Packages

jobs:
  build-webr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build webR binaries
        uses: r-wasm/actions/build-rwasm@v2
        with:
          packages: "local::."
          repo-path: _site

      - name: Upload webR binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: webr-repo
          path: _site/
          retention-days: 7
